#!/usr/bin/env python
from pathlib import Path
from tkinter.filedialog import askopenfilename
from pylbmisc.io2 import import_data
from pylbmisc.io2 import export_data

# -----
# PATHS
# -----

# project
root = Path(".")
data_dir = root / "data"

# ----
# UTILS
# ----


def import_generic_dataset(do_encryption=True):
    """
    Import latest dataset and set up proper symlinks.
    """
    msg = "Insert date of the data extraction " \
        "(YYYY-MM-DD) or leave blank to skip: "
    dataset_date = input(msg).replace("-", "_")
    gpg_ext = '.gpg' if do_encryption else ''
    if dataset_date != "":
        title = "Select DATA FILES to be imported and anonymized"
        initialdir = "/tmp"
        filetypes = [("Formati", ".csv .xls .xlsx .zip")]
        fpaths = askopenfilename(
            title=title, initialdir=initialdir,
            filetypes=filetypes, multiple=True
        )
        # import data
        dfs = import_data(fpaths)
        # save as a single excel file
        outfile = data_dir / f"raw_dataset_{dataset_date}.xlsx{gpg_ext}"
        export_data(x=dfs, path=outfile.absolute())
        # add symlink
        symlink = data_dir / f"raw_dataset.xlsx{gpg_ext}"
        if symlink.exists():
            symlink.rename(data_dir / f"old_raw_dataset.xlsx{gpg_ext}")
        symlink.symlink_to(outfile.relative_to(data_dir))



if __name__=="__main__":
    import_generic_dataset()
