#!/usr/bin/env python
import os
import shutil
from pathlib import Path
from tkinter.filedialog import askopenfilename

# ------
# PATHS
# ------

# project
root = Path(".")
data_dir      = root / "data"

def _setup_redcap_file(input_path, is_label, do_encryption):
    """
    Copia e crea i link per i file esportati da redcap (sia dati che labels)
    """
    gpg_ext = '.gpg' if do_encryption else ''
    outfile = data_dir / f"{input_path.name}{gpg_ext}"
    if is_label:
        symlink = data_dir / f"LABELS.csv{gpg_ext}"
        old_symlink = data_dir / f"OLD_LABELS.csv{gpg_ext}"
    else:
        symlink = data_dir / f"DATA.csv{gpg_ext}"
        old_symlink = data_dir / f"OLD_DATA.csv{gpg_ext}"
    # rm old symlink
    if symlink.exists():
        symlink.rename(old_symlink)
    # cp data
    if do_encryption:
        cmd = "gpg --encrypt --recipient lbraglia@gmail.com" \
            f" --output {outfile} {input_path}"
        os.system(cmd)
    else:
        shutil.copy(input_path, outfile)
    # add symlink
    symlink.symlink_to(outfile.relative_to(data_dir))


def import_redcap(do_encryption=True):
    """
    Import latest redcap export (both DATA and LABELS) and set up proper
    symlinks.
    """
    # tk-dialogbox
    title = "Select the two csvs for DATA and LABELS exported from RedCAP" \
        "'Data Exports, Reports, and Stats' -> 'Export Data'" \
        " -> 'Download raw data and labesls'"
    initialdir = "/tmp/"
    filetypes = [("Formati", ".csv")]
    fpaths = askopenfilename(
        title=title, initialdir=initialdir,
        filetypes=filetypes, multiple=True
    )
    if len(fpaths) != 2:
        msg = "Stoppo: devono essere selezionati 2 csv," \
            " uno per DATA e uno per LABELS."
        raise ValueError(msg)
    fpaths = [Path(p) for p in fpaths]
    labels = ["_DATA_LABELS_" in p.stem for p in fpaths]
    for i in range(len(fpaths)):
        _setup_redcap_file(input_path=fpaths[i],
                           is_label=labels[i],
                           do_encryption=do_encryption)



if __name__=="__main__":
    import_redcap()
